name: GHCR Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 清理 GHCR
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: user
          token: ${{ secrets.GHCR_CLEANUP_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository-name: ${{ github.repository }}
          keep-at-most: 5
