name: CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/chatgpt-ghibli-flow

jobs:
  ci-check-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install All Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Application Check
        run: pnpm build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            cd ${{ secrets.PROJECT_PATH_ON_SERVER }} || { echo "Failed to cd into project directory"; exit 1; }

            if [ ! -f ".env" ]; then
              echo "Error: .env file not found on the server in $(pwd). Deployment aborted."
              exit 1
            fi
            if [ ! -f "cookies.json" ]; then
              echo "Error: cookies.json file not found on the server in $(pwd). Deployment aborted."
              exit 1
            fi

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            IMAGE_TO_PULL="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

            docker pull "$IMAGE_TO_PULL"

            echo "Stopping existing container..."
            docker stop ghibli-flow-app || echo "Container ghibli-flow-app not found or already stopped."
            echo "Removing existing container..."
            docker rm ghibli-flow-app || echo "Container ghibli-flow-app not found."


            echo "Starting new container..."
            docker run -d \
              --name ghibli-flow-app \
              --restart unless-stopped \
              -p 3000:3000 \
              -v "${PWD}/cookies.json":/app/cookies.json:ro \
              -v "${PWD}/.env":/app/.env:ro \
              -e NODE_ENV=production \
              -e TERM=dumb \
              -e COOKIES_FILE_PATH=/app/cookies.json \
              "$IMAGE_TO_PULL"

            echo "Pruning old images..."
            docker image prune -f
            echo "🚀 Deployment completed successfully."
